Citizens edit event info
e1401/speck-academy-booking-app-client pull request #2
Opened 2019-05-31 11:23 UTC by isirjan

2019-05-31 11:46 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfo.js
> +        <form>
svi input elementi trebaju biti wrappani sa jednim form elementom.

2019-05-31 11:47 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfo.js
> +          <input type="text" value="Opišite svoj događaj..." />
ovo će vjerojatno biti textarea element

2019-05-31 11:47 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfoStyle.js
> +    height: auto;
zašto postavljaš height: auto?

2019-05-31 11:49 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfoStyle.js
> +    font-style: normal;
nepotrebno, "normal" je defaultna vrijednost font-style property-ja

2019-05-31 11:50 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfoStyle.js
> +    font-stretch: normal;
nepotrebno, "normal" je defaultna vrijednost font-stretch property-ja

2019-05-31 11:50 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfoStyle.js
> +    line-height: normal;
nepotrebno, "normal" je defaultna vrijednost font-height property-ja

2019-05-31 11:50 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfoStyle.js
> +    letter-spacing: normal;
nepotrebno, "normal" je defaultna vrijednost letter-spacing property-ja

2019-05-31 11:52 UTC, ispoljari commented on src/UI/citizens/components/edit-event-info/CitizensEditEventInfo.js
> +class CitizensEditEventInfo extends React.Component {
nemoj koristiti class komponentu, nego običnu funkcijsku komponentu u fazi developmenta static UI-ja (napomenuto više puta tijekom predavanja, ali i u uputama. Molim te baci još jednom na upute :=) )

2019-05-31 11:53 UTC, ispoljari requested changes
molim ispraviti kod prema komentarima

2019-06-10 08:57 UTC, e1401 commented
Older version of the code.

2019-06-10 08:57 UTC, closed without merging